---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statsd-sink
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: statsd-sink
    spec:
      containers:
        - name: statsd-sink
          image: prom/statsd-exporter:v0.8.1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: statsd-sink
  name: statsd-sink
spec:
  ports:
    - protocol: UDP
      port: 8125
      targetPort: 9125
      name: statsd-metrics
    - protocol: TCP
      port: 9102
      name: prometheus-metrics
  selector:
    service: statsd-sink
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ambassador-monitor
  labels:
    ambassador: monitoring
spec:
  selector:
    matchLabels:
      service: statsd-sink
  endpoints:
    - port: prometheus-metrics
