---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
  selector:
    service: ambassador
