---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  label:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 8080
  selector:
    service: ambassador
