---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 8080
  selector:
    service: ambassador
