apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    environment: dev
    hello: world
spec:
  containers:
  - name: hello
    image: speedwing/hello
    ports:
    - containerPort: 8080
