apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  labels:
    prometheus: main
spec:
  replicas: 1
  serviceMonitorSelector:
    matchLabels:
      ambassador: monitoring
      prometheus/global: "true"
