---
apiVersion: v1
kind: Service
metadata:
  name: other-webapp
spec:
  selector:
    app: other-webapp
  ports:
    - port: 80
      name: other-webapp
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: other-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: other-webapp
  template:
    metadata:
      labels:
        app: other-webapp
    spec:
      containers:
      - name: other-webapp
        image: speedwing/ws2-simple-app:v1
        env:
          - name: DEPLOYMENT_GROUP
            value: prod
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
