apiVersion: v1
kind: Pod
metadata:
  name: dodgy-pod
  labels:
    pod-template-hash: "2294540316"`
    run: hello-world
spec:
  containers:
  - name: hello
    image: nemo83/hello
    ports:
    - containerPort: 8080
