apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
    environment: dev
    team: personalization
    run: manual
spec:
  containers:
  - name: hello
    image: speedwing/hello
    ports:
    - containerPort: 8080
