---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
    stage: live
    team: "team_AT_email.com"
spec:
  containers:
    - name: hello
      image: speedwing/hello:v1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-dark
  labels:
    app: hello-world
    stage: dark
    team: "team_AT_email.com"
spec:
  containers:
    - name: hello
      image: speedwing/hello:v2
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world-canary
  labels:
    app: hello-world
    stage: canary
    team: "team_AT_email.com"
spec:
  containers:
    - name: hello
      image: speedwing/hello:v2
      ports:
        - containerPort: 8080
