apiVersion: v1
kind: Pod
metadata:
  name: hello-world-unhealthy
  labels:
    app: hello-world
spec:
  containers:
  - name: hello
    image: speedwing/hello:v1-unhealthy
    ports:
    - containerPort: 8080
