apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002
      targetPort: 3000
  selector:
    app: grafana
